JUDGE0_TELEMETRY_ENABLE=false
ENABLE_WAIT_RESULT=true
ENABLE_BATCHED_SUBMISSIONS=true
MAX_SUBMISSION_BATCH_SIZE=50
ALLOW_ORIGIN=
REDIS_HOST=judge0-redis
REDIS_PORT=6379
REDIS_PASSWORD=judge0-redis-password
POSTGRES_HOST=judge0-db
POSTGRES_PORT=5432
POSTGRES_DB=judge0
POSTGRES_USER=judge0
POSTGRES_PASSWORD=judge0-postgres-password
RAILS_ENV=production
RAILS_MAX_THREADS=5
